### ISSUE TITLE
ruma_api(query) breaks for fields that can be structs

### ISSUE THREAD

**Issue by florianjacob** [ruma/ruma-api-macros#3]
Serializing the [`filter` argument of `sync_events`](https://github.com/ruma/ruma-api-macros/blob/ef32a2f9c1d815c40af8dea159518624476135e8/src/api/mod.rs#L122) can lead to an unsupported value error by the `serde_urlencoded` library.

This happens if [the Filter enum](https://github.com/ruma/ruma-client-api/blob/72e6dc7ad7fd848f0cc1285002c8c5b2e9d488a1/src/r0/sync.rs#L266) is a [FilterDefinition](https://github.com/ruma/ruma-client-api/blob/72e6dc7ad7fd848f0cc1285002c8c5b2e9d488a1/src/r0/filter.rs#L141) struct and not a `FilterId` String.

Then, the [call to serde_urlencoded::to_string](https://github.com/ruma/ruma-api-macros/blob/ef32a2f9c1d815c40af8dea159518624476135e8/src/api/mod.rs#L122) will break, as it can't serialize a full struct to a single query parameter.

The spec mandates the field to contain “the ID of a filter created using the filter API or a filter JSON object encoded as a string.”, so the intermediate step of encoding the object to json before url-encoding it is missing here.

I don't know how this should be solved properly, maybe with an additional kind of proc macro marker like [ruma_api(json_encode)] or something, but then this has to work as well with filter ids.

I have a workaround, though: As [the spec detects whether the filter is JSON or a filter ID by looking at whether the String begins with {](https://matrix.org/docs/spec/client_server/r0.3.0.html#get-matrix-client-r0-sync), you can cheat by serializing your filter to json yourselve and give this to ruma as a filter id, like this:

```
    let filter_definition = …;
    let filter_string = serde_json::to_string(&filter_definition).unwrap();

    use r0::sync::sync_events;
    let response = await!(sync_events::call(
            client.clone(),
            sync_events::Request {
                filter: Some(sync_events::Filter::FilterId(filter_string)),
                since: None,
                full_state: None,
                set_presence: None,
                timeout: None,
            }
            )).unwrap();
```

**Comment by jplatte** [comment]
I have an idea on how to fix this in ruma-client-api. We could introduce an `enum FilterArg` with custom (de)serialization logic in `r0::sync::sync_events`.

**Comment by florianjacob** [comment]
@jplatte Makes sense. While looking at ruma-client-api, I discovered that there already is the `Filter` enum which *seems* to had that intention, but is missing the appropriate (de)serialization logic: https://github.com/ruma/ruma-client-api/blob/master/src/r0/sync/sync_events.rs#L70

**Comment by jplatte** [comment]
Sounds like it's just adding the custom (de)serialization logic then :)

If you want, you can open a new issue over at ruma-client-api and close this one. I'm fairly certain that this doesn't need support from ruma-api-macros.
